# Generated by Django 5.2.4 on 2025-07-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='api.child'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
