# Generated by Django 5.2.4 on 2025-07-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_child_user_alter_customuser_role_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
    ]
