# Generated by Django 5.2.4 on 2025-07-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='parent_id',
            new_name='parent_name',
        ),
    ]
