# Generated by Django 5.2.4 on 2025-07-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_parent_id_child_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='myClass', to='api.child'),
        ),
    ]
