# Generated by Django 5.2.4 on 2025-08-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_classroom_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
