# Generated by Django 5.2.4 on 2025-08-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_classroom_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
