# Generated by Django 5.2.4 on 2025-08-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='repeat_days',
            field=models.CharField(blank=True, help_text='MO,TU,WE,TH,FR,SA,SU', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meetUrl', models.URLField(blank=True, null=True)),
                ('isCanceled', models.BooleanField()),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='api.classroom')),
            ],
        ),
    ]
