# Generated by Django 5.2.4 on 2025-08-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_classroom_repeat_days_classsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
