# Generated by Django 5.2.4 on 2025-08-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_teacher_google_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
