# Generated by Django 5.2.4 on 2025-08-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_teacher_google_access_token_teacher_token_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='token_expiry',
        ),
    ]
