# Generated by Django 5.2.4 on 2025-08-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_teacher_google_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='classRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.classroom'),
        ),
    ]
