# Generated by Django 5.2.4 on 2025-08-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='session_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
