# Generated by Django 5.2.4 on 2025-08-23 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_classroom_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('childCommitment', models.TextField(blank=True, null=True)),
                ('childDifficulties', models.TextField(blank=True, null=True)),
                ('childVictory', models.TextField(blank=True, null=True)),
                ('childSolution', models.TextField(blank=True, null=True)),
                ('studyLesson', models.CharField(blank=True, max_length=100, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.child')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.teacher')),
            ],
        ),
    ]
