# Generated by Django 5.2.4 on 2025-08-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='module',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
